env:
  global:
    - GIT_NAME="Travis-Deploy"
    - GIT_EMAIL="info+github@lazyfrosch.de"
    - GH_REF="git@github.com:lazyfrosch/training-debian-packaging.git"
sudo: false
language: python
cache: pip
before_script:
- pip install mkdocs
- pip install MarkdownHighlight
- openssl aes-256-cbc -K $encrypted_cc1c7b2727a7_key -iv $encrypted_cc1c7b2727a7_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
- git remote add deploy "${GH_REF}"
- git fetch deploy && git fetch deploy gh-pages:gh-pages
script:
- mkdocs build
- find site/
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    echo "Pushing to github"
    PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name deploy
    git push deploy gh-pages
  fi
