site_name: Debian Packaging Training
#theme: readthedocs
repo_url: https://github.com/lazyfrosch/training-debian-packaging
site_author: Markus Frosch <markus.frosch@netways.de>
copyright: >-
  <p>Copyright (c) 2018 <a href="mailto:info@netways.de">NETWAYS GmbH</a></p>
  <p><a href="https://github.com/lazyfrosch/training-debian-packaging">Sourcecode on GitHub</a></p>
  <p><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" />
  </a><br />This work is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0
  International License</a>.</p>

pages:
  - Introduction: index.md
  - Admin Guide:
    - CLI Tools: admin/index.md
    - Repositories: admin/repositories.md
  - Developer Guide:
    - Build Environment: dev/index.md
    - Source Package: dev/source.md
    - Building Packages: dev/building.md
  - About:
    - References: about/references.md
    - License: about/license.md
